### ISSUE TITLE
Styling for a button, button etc

### ISSUE THREAD

**Issue by badcat** [kevquirk/simple.css#10]
In the demo page, https://simplecss.org/demo you styled for `a button, button`...  but the the element button must not appear as a descendant of the a element to be W3C valid.
https://validator.w3.org/nu/?doc=https%3A%2F%2Fsimplecss.org%2Fdemo

**Comment by kevquirk** [comment]
I know. I added a note right after the button saying it will work but it's invalid HTML.

**Comment by badcat** [comment]
I get that.  I guess I posed the point incorrectly. We can't style an anchor link to look like a button? (with just `a`?)

**Comment by kevquirk** [comment]
I've removed the linked button section from the site entirely - a couple of people have mentioned this and to be frank, it's not in keeping with the aims of the project.

I'm thinking about adding an additional "simple+" stylesheet that adds some sensible classes (buttons, notification banners etc). Separate stylesheet so that it remains optional for those who want to use it.

Thanks for the feedback.

**Comment by lucasjose501** [comment]
> 
> 
> I'm thinking about adding an additional "simple+" stylesheet that adds some sensible classes [..]

In this case, this simple+ stylesheed will only contain some classes and use simple.css as requirement?
If that's the case, perfect! At least for me. I like to use sass and import css separated to have a clean project

Loving the work btw. Congratulations.

**Comment by badcat** [comment]
Fair enough :) thank for your work on this!

**Comment by kevquirk** [comment]
> In this case, this simple+ stylesheed will only contain some classes and use simple.css as requirement?

Yeah, pretty much.

> Loving the work btw. Congratulations.

Thanks. :-)
