### ISSUE TITLE
Have all font-sizes calculated from --base-fontsize

### ISSUE THREAD

**Issue by peterhop** [kevquirk/simple.css#118]
Some font-sizes are calculated from --base-fontsize and some are not. To be consistent all should be calculated from --base-fontsize.

**Comment by lkhrs** [comment]
Which version of Simple.css are you using? We don't use `--base-fontsize` in v2.

**Comment by peterhop** [comment]
Hi Luke,

The simple-v1.css uses —base-fontsize, see below. I’m a bit confused by the version numbers. The simplecss GitHub main page says that simple-v1.css is actually version 2, see further below. So I assumed that simple-v1.css was the latest version. Is there a more recent version that doesn’t use —base-fontsize?

Cheers,
Peter

[Image.jpeg]


[Image.jpeg]
________________________________

**Comment by lkhrs** [comment]
The images you attached didn't get uploaded, but I see what you mean. I believe you are referring to the commit message on the v1 file. 

Please see the [Releases](https://github.com/kevquirk/simple.css/releases) page for the latest version 🙂

**Comment by peterhop** [comment]
Hi Luke,

Yes I downloaded the latest simple-v1.css and found —base-fontsize there. And the same issue with some font-sizes not being calculated from —base-font size. But I guess if the issue is closed it’s closed.

Cheers
________________________________

**Comment by lkhrs** [comment]
Hi Peter,

I’m sorry if I’m misunderstanding you here—I’m under the impression you would like to keep using v1 instead of v2? v1 is effectively frozen, it’s available in the repository to ease the transition from v1 to v2, which was released 8 months ago.

All improvements and fixes are focused on v2, the latest version of which does not use the —base-font-size variable for fonts. Here is a direct link to the release page with downloads for v2.1.1: https://github.com/kevquirk/simple.css/releases/tag/v2.1.1

Let me know if this helps!

**Comment by kevquirk** [comment]
For context here, I decided to remove `--base-font-size` from V2 because it was using the golden ratio, but it felt way too big to me, especially on mobile.
