### ISSUE TITLE
button inside link is not valid HTML

### ISSUE THREAD

**Issue by jmuheim** [kevquirk/simple.css#120]
Thanks for creating simple.css, it's a nice helper for starting a new project.

However, you suggest putting a button into a link:

![CleanShot 2022-10-02 at 11 23 53@2x](https://user-images.githubusercontent.com/1814983/193447330-7bd7e574-f8c6-4707-b184-a17ae1b836ea.png)

But this is not valid HTML:

![CleanShot 2022-10-02 at 11 25 06@2x](https://user-images.githubusercontent.com/1814983/193447373-5c7016ab-8eb6-40b5-a4a5-b2e5a522abaf.png)

Source: https://stackoverflow.com/questions/6393827/can-i-nest-a-button-element-inside-an-a-using-html5

Just wanted to let you know.

**Comment by kevquirk** [comment]
I'm aware it's not valid HTML, but people still want to do it, so I provided a solution. The common way of doing this of course is to add a `button` class to a standard link and format it to look like a button. Because simple.css is classless, we don't have that.

I am, however, looking at adding some simple classes that will (hopefully) add value to people. Things like buttons, notice boxes etc. I just haven't got around to working on it yet. When I get time to sit down and do this, it should negate the need for this wonky HTML.

Thanks.

**Comment by jmuheim** [comment]
Thanks for clarifying this. 👍
