### ISSUE TITLE
Button inside A-element gives HTML validation error

### ISSUE THREAD

**Issue by krompaco** [kevquirk/simple.css#133]
Hi and thanks for a great job!

I noticed in the current version that the demo page gives an error for this:

```
Error: The element button must not appear as a descendant of the a element.

[From line 96, column 34; to line 96, column 41](https://validator.w3.org/nu/#l96c41)

mple.com"><button>I’m a
```
Not sure how to change it to though...

**Comment by kevquirk** [comment]
Yeah, that's because a `button` element with a link isn't valid HTML (although it does work). Semantically, as I understand it, a `button` element is for a function, like submitting a contact form, it's not for links. Therefore it's not valid.

The "correct" way to do this so that it's valid HTML is to create a normal link with a class of something like `button` then format that class with CSS to make it look like a button. That would pass validation, I imagine.

Problem is, this is a classless stylesheet, so it's something folks can add in their custom CSS. Something like this would work:

```
<a class="button" href="https://example.com>This is a linked button</a>
```

With the following CSS so it matches the design of Simple.css:

```
.button {
    border: none;
   border-radius: 5px;
   background-color: var(--accent);
   font-size: 1rem;
   color: var(--bg);
   padding: 0.7rem 0.9rem;
   margin: 0.5rem 0;
}

.button:hover {
    filter: brightness(1.4);
}
```

Hope this helps.
