### ISSUE TITLE
Altering Body tag's max-width value

### ISSUE THREAD

**Issue by Bestbynature** [kevquirk/simple.css#160]
In my own CSS file, how do I change the max-width value for the body tag? It is currently set at 45rem.

I have tried 

```
:root {
    --max-width: 100%;
  }
```
  
Then I tried declaring the max-width again using
  
`  body { max-width: 100%}`
  
  none has worked.

**Comment by walterdavis** [comment]
Try making these changes on `html`. That's where I have found other "base" properties.

**Comment by lkhrs** [comment]
@Bestbynature try changing this value on [line 73](https://github.com/kevquirk/simple.css/blob/3430cd83b1c33f19bb0b9bdac0dabc2ecf658242/simple.css#L73):
`grid-template-columns: 1fr min(45rem, 90%) 1fr;`

We use grid to set 3 columns:
1. A fractional column
2. A column with a width of either 45rem or 90% of the parent, whichever is smaller
3. A fractional column

To set the body width to 100%:
`grid-template-columns: 1fr 100% 1fr;`

I am closing this issue because this is a support request, but feel free to reply back if you need more assistance with changing the body width.
