### ISSUE TITLE
More Content Space

### ISSUE THREAD

**Issue by GitToTheHub** [kevquirk/simple.css#190]
Hi,

I'm using your framework for a web app, where i present data in tables, which can get huge.
The visible space for showing data is very narrow. Can you add an option to widen the space?

Here is an example:

<img width="1280" alt="Bildschirmfoto 2024-03-31 um 17 27 26" src="https://github.com/kevquirk/simple.css/assets/13721821/3870cb77-fedf-4412-a77f-9286cc60ba89">

It would be nice if i could give my app more room for showing data.

**Comment by kevquirk** [comment]
As this is a unique use case to your project, it's something that would require custom CSS that you would need to implement yourself. Simple CSS isn't designed to have stuff escape the main element so that it can be full-width. You'd have to play around with the grid layout in order to make this work.

**Comment by kevquirk** [comment]
As this is a unique use case to your project, it's something that would require custom CSS that you would need to implement yourself. Simple CSS isn't designed to have stuff escape the main element so that it can be full-width. You'd have to play around with the grid layout in order to make this work.

**Comment by kevquirk** [comment]
I'm not saying it's uncommon. I'm saying it's outside of the scope of Simple CSS. The whole point of it is to be as simple as possible. Providing the most basic of CSS that people can then expand upon.

**Comment by GitToTheHub** [comment]
I understand and I like your approach. I thought this change would fit in Simple CSS but if not, it's ok.

Could you maybe give me a hint how to make the content bigger?
