### ISSUE TITLE
Support for rtl languages

### ISSUE THREAD

**Issue by bas080** [kevquirk/simple.css#205]
It would be nice to have out of the box support for rtl languages. That would likely entail a list of selectors that match on `[lang=ar], [lang=<lang>], ...`.

Another possibility is to at least support the `dir=rtl` attribute.

**Comment by lkhrs** [comment]
We cannot feasibly support each RTL language individually but we do have a couple of selectors for `dir="rtl"`. I'm open to continuing our support for `dir="rtl"` where it makes sense.

I added `dir="rtl"` to the body element on our test page locally and I’m struggling to find an issue. Can you specifically list the issues you’re having with RTL support as is?

**Comment by bas080** [comment]
I have a project where the lang is only defined. When I tested the dir attribute things seemed to work because of browser defaults.

I have noticed some tools supporting `text-align: right` when an rtl lang is defined. That might explain my confusion. 

The list of rtl languages doesn't seem too long when supporting most common rtl languages.

- Arabic: ar
- Hebrew: he
- Persian (Farsi): fa
- Urdu: ur
- Yiddish: yi
- Pashto: ps
- Dari: fa-AF
- Kurdish (Sorani): ckb
- Sindhi: sd
- Divehi (Maldivian): dv
- Syriac: syr (no two-letter code)
- N'Ko: nqo (no two-letter code)

Nice to have? YAGNI? Your call.

**Comment by lkhrs** [comment]
Yeah I don't think those tools are supporting RTL correctly. Using `text-align` shouldn't be necessary in most cases. Best practice is to use the `dir` attribute and stick to logical properties in CSS as much as possible, e.g. `end` instead of `right`. Changing the `direction` property in CSS is discouraged because it doesn't affect all elements, and if the CSS file doesn't load it does nothing. 

Ahmad Shadeed has a fantastic resource for RTL styling: https://rtlstyling.com/posts/rtl-styling

I'm closing this for now but please respond back if you encounter an issue related to how Simple.css handles `dir="rtl"`.
