### ISSUE TITLE
::backdrop

### ISSUE THREAD

**Issue by lekoala** [kevquirk/simple.css#214]
Having ::root, ::backdrop makes the rule invalid in browsers not supporting ::backdrop
https://caniuse.com/mdn-css_selectors_backdrop (so, mostly ios < 15.4)

Would you consider splitting the rule? it would lead to a slight duplication of the code but it would improve support

**Comment by lkhrs** [comment]
Will take a look at this, but initial thought is that `::backdrop` has been baseline since 2022 and I think two years is long enough. iOS 15.4 came out in March 2022. 

However, if it's causing `:root` to fail that's an issue. I'm not sure if we need those two selectors combined in the first place but I'll find out.

**Comment by lekoala** [comment]
yes it's easy enough to add the variables again in my project anyway (i'm aiming to support some older ios versions, basically anything since js modules support) so I understand if you want to drop support for older browsers, but it doesn't seem like a big effort to split the rule :-)

i'm not even sure it makes a lot of sense to have the css variables declared for the backdrop

most if the time, i only have one css variable for the backdrop, and that's the backdrop color :-)

**Comment by lkhrs** [comment]
Yep, turns out `::backdrop` inherits those variables anyway because it inherits from `<dialog>`. Thanks for bringing this up :)
