### ISSUE TITLE
Do not set font globally

### ISSUE THREAD

**Issue by andreasKroepelin** [kevquirk/simple.css#27]
This definition:
https://github.com/kevquirk/simple.css/blob/68ddf6a1008b2f0418268156e014643deaab9791/simple.css#L51-L54
makes syntax highlighting in `<pre>` blocks impossible because every `<span>` that would define a local highlighting colour leads to the global sans serif font.
Is there any deeper reason behind setting the font globally?

**Comment by kevquirk** [comment]
I did this so that I don't have to add a long list of elements to make them use the sans font.

Anyway, it was a simple fix to add `pre span` to the list of items that use the mono font. Just pushed it.

**Comment by andreasKroepelin** [comment]
Awesome, thanks for the quick fix!
Also thank you for simple.css in general, I happily use it for my personal website :)

**Comment by kevquirk** [comment]
No problem. Thanks for reporting it - glad you're enjoying Simple.css :-)

**Comment by Pinjasaur** [comment]
Ran into this and was going to create an issue but found this one already existed and the `pre span` override.

Any reason for not just doing a

```css
html {
  font-family: var(--sans-font);
}
```

so the font declaration is inherited through the cascade? The `pre span` works for the syntax highlighting scenario but an override pattern e.g., `span pre` has its downsides.

For context, I was integrating simple.css with highlight.js in a personal project a few days before this issue was created. I overrode it similarly: https://github.com/Pinjasaur/bic-example/commit/257ae0451b59021a9a6dffc31c5dff1eaf0bbffb

**Comment by kevquirk** [comment]
@Pinjasaur that's a great point and a more elegant solution for sure. I've just pushed a fix for this. Should be live in 10 minutes or so once the CSS is minified and pushed to the CDN.
