### ISSUE TITLE
The dark mode is installed by default in automatic ?

### ISSUE THREAD

**Issue by Azaretdodo** [kevquirk/simple.css#44]
Hello,

The dark mode is installed by default in automatic ?

Thank you in advance for yours answer,

Have a nice Wednesday from the France the weather is cloudy and it is fourteen to three here,

Regards.

Azaretdodo.

**Comment by samal-rasmussen** [comment]
simple.css uses the prefers-color-scheme media query which gets the setting from the os settings, so whatever you have configured your os to will be the default:
https://developer.mozilla.org/en-US/docs/Web/CSS/@media/prefers-color-scheme

You cannot set prefers-color-scheme directly with your own code:
https://stackoverflow.com/questions/63144602/edit-prefers-color-scheme-value-to-force-dark-mode

But you can use two extra light and dark css variables in order to create a way to set the light and dark mode in your own code. Lots of variations on how to do this here:
https://stackoverflow.com/questions/56300132/how-to-override-css-prefers-color-scheme-setting

**Comment by Azaretdodo** [comment]
Thank you for your answer,

I have backup your answer,

Have a nice thursdays from th France the weather is cloudy and it is fiveteen to twenty nine here,

Regards.


Dorian Rosse.
________________________________
