### ISSUE TITLE
Smooth Animations Gone?

### ISSUE THREAD

**Issue by dugancatwit** [kevquirk/simple.css#55]
In v1, when adding drop shadow or scale changes on hover, my website would automatically smoothly animate between those values, but it doesn't seem to be the case in v2? v2 just has an instant change from one to another. If this is intentional, is there a way for me to opt back into this feature? Thanks

**Comment by kevquirk** [comment]
It was intentional. I retrospectively decided that the transition animation was a little too opinionated.

Adding it back is really simple. Create a custom CSS file ([more info here](https://simplecss.org/getting-started#make-changes)) and add transition: 0.4s; to any element you want the transition animation.

For example, if you want the animation on hover effect for links, do this:

a {
transition: 0.4s;
}
