### ISSUE TITLE
Fix link button styling

### ISSUE THREAD

**Issue by troxler** [kevquirk/simple.css#59]
Hi. I maintain a [list of CSS frameworks](https://github.com/troxler/awesome-css-frameworks) and people created both an issue and a PR to consider Simple.css. The addition is tracked here: https://github.com/troxler/awesome-css-frameworks/pull/87

I had a look at Simple.css and stumbled upon your styling of links that look like buttons. You seem to encourage/support two different ways to achieve them which both are bad practice.

* In your demo, you use `<button onclick="window.location.href='https://example.com';">` instead of a link. Falling back to JavaScript for a simple thing such as a link is not a good approach.

* simple.css contains a selector `a button` that targets buttons within links. Links are not allowed to contain interactive elements which a button clearly is.

Please provide a valid way to achieve links that look like buttons.

**Comment by kevquirk** [comment]
Hi there,

I wouldn't say I encourage the use of JS in this regard, but you're right, it's far from an elegant solution. A class would obviously be easier here, but Simple.css is classless so...

Anyway, I've made some changes to how buttons are marked up in the demo and I have also removed `a button` from Simple.css:

```
<a href="https://example.com">I'm a hyperlink</a>

<button>I'm a button</button>

<a href="https://example.com"><button>I'm a button with a link</button></a>
```

Hopefully this satisfies the requirement.

**Comment by kevquirk** [comment]
I'm fresh out of ideas then - without using a class, I don't know a way of doing it. Happy to take your advice if you know a better way...

**Comment by troxler** [comment]
If you insist on being absolutely free of classes, then you might want to take inspiration in [similar frameworks](https://github.com/troxler/awesome-css-frameworks#class-less). For example, MVP.css uses something like `<a href><b>Link that looks like a button</b></a>`. As the `b` element "[is used to draw the reader's attention to the element's contents](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/b)", this nicely translates to what the button-styled link is supposed to do. So that may be one way to achieve that using proper semantics.

**Comment by kevquirk** [comment]
The b tag is used for bold text though, at which point the whole thing becomes ambiguous and confusing.

I'd much rather use some HTML that isn't recommended, but works perfectly well, than an ambiguous work around.

**Comment by troxler** [comment]
> The b tag is used for bold text though, at which point the whole thing becomes ambiguous and confusing.

That might have been the case historically, but is not true anymore according to the [specification](https://html.spec.whatwg.org/multipage/text-level-semantics.html#the-b-element).

> I'd much rather use some HTML that isn't recommended, but works perfectly well, than an ambiguous work around.

That is a limitation of "classless" CSS frameworks. Either you only use UI elements that are considered in the HTML spec, or you make a tradeoff. Links that look like buttons is not something that has been part of the spec.

**Comment by pbarney** [comment]
@kevquirk, I totally get the frustration. This is one of those cases where the specs interfere with purity, and normally, I would just say "screw it, full steam ahead." But the one problem we're going to have with `<a><button>` is that if it's within a `<form>`, it will trigger a form submit instead of going to the `href`. The only ways around that is to either use javascript to intercept the click or to have an arbitrary rule that you can't use `<a><button>` inside a `<form>`.

But here's a thought... you have two button styles: 1. the filled-in `<button>` and 2. the transparent `<nav><button>`.  How about replacing `<a><button>` with `<nav><a>` and using the filled-in style, and then using `<header><nav><button>` for the transparent buttons (as it seems they're most widely used as header navigation)?

**Comment by pbarney** [comment]
Another idea: use the `role` attribute of `<a>`:

```
<style>
a[role="button"] {
    /* your button styling */
}
</style>

<a role="button" href="/index.html">home</a>
```

This is 100% valid and no extra markup required.

**Comment by kevquirk** [comment]
If we use `role` we might as well use a class.

I'm thinking about changing the premise of Simple.css so that it includes some very basic classes for things like buttons, notice boxes etc.

It will still work classless, so people can use it on semantic HTML, but it will add a couple of bells and whistles that people can use.

**Comment by Yenya** [comment]
Hello,

(related to #61 as well)

<a role="button"> has different size than <button>. I often want to use these elements together, with button handled by local Javascript, and <a> leading to a different page. So that I need them to fit together, to have the same size. For now, I am trying to use <button formattion=...> instead of <a role="button">, but I think the <a> leading to a different page would fit the "classless css" paradigm better.

**Comment by waldyrious** [comment]
> If we use `role` we might as well use a class.

Why do you think so? IMO there's a difference in that the name of class is arbitrary, whereas there are [standard ARIA roles](https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/ARIA_Techniques), including `button`.

**Comment by troxler** [comment]
Semantically, a link that looks like a button is not a button. Links and buttons behave differently and have different features. They are different things after all. And while using [`role="button"` on an anchor element is possible in some use cases](https://www.w3.org/WAI/ARIA/apg/patterns/button/examples/button/), it is incorrect to use it on an actual link.

**Comment by pbarney** [comment]
I think the thing people are missing here (from my point of view) is that simple.css isn't supposed to be a full-scale css framework, but a way to add nice styling to a generic web page. It may not be possible to become all things to all people, otherwise you end up like Tailwind or Bootstrap.

I came to simple.css because I hand-write HTML pages for my own reference pages and it's nice to have them automatically styled without making it a major project.

**Comment by kevquirk** [comment]
@pbarney exactly this.

FWIW, [we recently added](https://simplecss.org/introducing-simple-classes) a `.button` and `.notice` class to the stylesheet, so this conversation is now moot, I think.
