### ISSUE TITLE
make image resizable

### ISSUE THREAD

**Issue by laoshaw** [kevquirk/simple.css#83]
I have some images need to be auto-resized, I put

```
img {
max-width: 100%;
height: auto;
}
```
at the root level of simple.css, it worked well for me, should this be the default?

**Comment by kevquirk** [comment]
Simple.css already has the following:

```
main img,
main video {
  max-width: 100%;
  height: auto;
  border-radius: 5px;
}
```

So any image added within the `main` tag will have this applied. My thinking originally was to apply this to stuff in `main` only so that images inside pages/posts are formatted nicely, but folks can define their own CSS for other images, like in the header and footer.

But yeah, maybe you're right, top level would probably work better for this. Thanks.
